<br/>
        <?php
           foreach ($this->cats->findMainCats() as $cat){
            ?>
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th colspan="6"><h3><?php  echo $cat->getCategory_name() ?><h3></th>
                  </tr>
                </thead>
                <?php   
                    foreach ($this->cats->findChildCategory($cat->getCategory_id()) as $child){
                        ?>
                        <tr>
                            <th colspan="6"><h3><?php  echo $child->getCategory_name();?><h3></th>
                        </tr>
                        <tr>
                            <td>title</td>
                            <td>post</td>
                            <td>lastReply</td>
                            <td>views</td>
                            <td>replies count</td>
                            <td>post count</td>
                          </tr>
                      <?php  
                    foreach ($this->thread->findByCat($child->getCategory_id()) as $thread){
                        ?>
                         <tr>
                            <td><?php echo $thread->getThread_title(); ?></td>
                            <td><?php
                                 $data = substr($thread->getThread_body(), 0, 60);
                                 echo $data."... More";
                              ?></td>
                            <td>lastReply</td>
                            <td>views</td>
                            <td>replies count</td>
                            <td>post count</td>
                          </tr>
                        <?php

                    }
                ?>
               <?php } ?>
                   </tbody>
                </table>
            <?php
        }
        ?>

