<br/>
<h3><?php  echo $this->Parcat->getCategory_name() ?></h3>
           <table class="table table-striped">
           		<tr>
           			<th colspan="6" class="mainCat"><h3><?php  echo $this->cat->getCategory_name() ?><h3></th>
        
           		</tr>
                <?php   
                  //sub category
                        ?>
                        <tr>
                            <td>title</td>
                            <td>post</td>
                            <td>views</td>
                            <td>replies count</td>
                            <td>post count</td>
                          </tr>
                      <?php  
                    foreach ($this->threads as $thread){  //thread
                        ?>
                         <tr>
                            <td><a href="<?php echo $this->baseUrl()?>/thread/thread/id/<?php echo $thread->getThread_id(); ?>"><?php echo $thread->getThread_title(); ?></td>
                            <td><?php
                                 $data = substr($thread->getThread_body(), 0, 60);
                                 echo $data."... More";
                              ?></td>
                            <td>views</td>
                            <td>replies count</td>
                            <td>post count</td>
                          </tr>
                        <?php           
                          }
                ?>
                   </tbody>
                </table>
            <?php
        ?>

