<br/>
<h3><?php  echo $this->Parcat->getCategory_name() ?></h3>
   <?php 
       if($this->cat->getCategory_state()!=0){
   ?>

    <a href="<?php echo $this->baseUrl() ?>/thread/add/id/<?php  echo $this->cat->getCategory_id() ?>" class="btn btn-danger pull-right">Add New Thtread</a>
    <?php } ?>
          <p class="clearfix"></p>
           <table class="table table-striped">
           		<tr>
           			<th colspan="6" class="mainCat">
                <h3>
                  <?php
                     if($this->cat->getCategory_state()==0){
                        echo "<img src='".$this->baseUrl()."/img/lock.png' class='cat_im'/>" ;
                      }else{
                        echo "<img src='".$this->baseUrl()."/img/open.png' class='cat_im'/>" ;
                      }

                  ?>
                  <?php  echo $this->cat->getCategory_name() ?><h3>
                </th>
        
           		</tr>
                <?php   
                  //sub category
                        ?>
                        <tr>
                            <td></td>
                            <td>title</td>
                            <td>post</td>
                            <td>views</td>
                            <td>replies count</td>
                          </tr>
                      <?php  
                    foreach ($this->threads as $thread){  //thread
                        ?>
                         <tr>
                            <td>
                              <?php
                                 if($thread->getThread_state_id()==1){
                                   echo "<img src='".$this->baseUrl()."/img/file.png' class='cat_im'/>" ;

                                 }else{
                                   echo "<img src='".$this->baseUrl()."/img/filelo.png' class='cat_im'/>" ;

                                 } 
                              ?>
                            </td>
                            <td><a href="<?php echo $this->baseUrl()?>/thread/thread/id/<?php echo $thread->getThread_id(); ?>"><?php echo $thread->getThread_title(); ?></td>
                            <td><?php
                                 $data = substr($thread->getThread_body(), 0, 60);
                                 echo $data."... More";
                              ?></td>
                            <td><?php  echo $thread->getViews() ?></td>
                            <td> <?php echo $this->threadreplay->findReplyThread($thread->getThread_id()) ?></td>
                          </tr>
                        <?php           
                          }
                ?>
                   </tbody>
                </table>
            <?php
        ?>

