</div>
        <footer>
            <div class="container">
                <div class="logo pull-left">
                    <img src="<?php echo $this->baseUrl() ?>/img/o.png" alt="">
                </div>
                <p class="clear"></p>
            </div>
        </footer>
  </div>
<?php $this->headTitle()->append('page'); ?>
<?php $this->headTitle()->prepend('SomePage'); // place before ?>
<?php echo $this->headScript() ?>