<div class="container-fluid bg">
        <header>
            <div class="container">
                <div class="logo pull-left">
                    <img src="<?php echo $this->baseUrl() ?>/img/o.png" alt="">
                </div>
                <div class="user_block pull-right">
                    <?php
                        if(!empty($this->user_name)){
                            echo"<ul class='border'>";
                            echo"<li> UserName : " .$this->user_name."</li>";
                            echo"<li> UserEmail : " .$this->user_email."</li>";
                           /* var_dump($this->user_type);exit();*/
                            if($this->user_type=="admin"){
                            echo"<li> <a href='".$this->baseUrl()."/admin'> admin Panel</a>";

                            }

                            echo"<li><a href='".$this->baseUrl()."/auth/logout'> Logout </a></li>";
                            echo"</ul>";
                        }else{
                          echo $this->form2;
                        }
                     ?>
                </div>
            </div>
        </header>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Fourm</a>
                </div>
                <ul class="nav navbar-nav">

                    <?php if( $this->user_type=="admin"){?>
                        <li class="active"><a href="<?php echo $this->baseUrl() ?>">Site</a></li>
                        <li><a href="<?php echo $this->baseUrl() ?>/Users/list">Users</a></li>
                        <li><a href="<?php echo $this->baseUrl() ?>/Category/">Categories</a></li>
                        <li><a href="<?php echo $this->baseUrl() ?>/Thread/">Threads</a></li>
                    <?php  }else{ ?>
                        <li class="active"><a href="<?php echo $this->baseUrl() ?>">Home</a></li>
                    <?php  } ?>
                </ul>
            </div>
        </nav>
        <div class="container content">
