<div class="container-fluid bg">
        <header>
            <div class="container">
                <div class="logo pull-left">
                    <img src="<?php echo $this->baseUrl() ?>/img/o.png" alt="">
                </div>
            </div>
        </header>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">WebSiteName</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                    <li><a href="#">Page 3</a></li>
                </ul>
            </div>
        </nav>
        <div class="container content">
	