<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
</head>
	<body>
		<?php echo $this->partial('_header.phtml',  array (
  			  'user_name' => $this->user_name,
  			  'user_email' => $this->user_email,
  		)
	);
 ?>
    	<?php echo $this->layout()->content; ?>

        
		<?php echo $this->partial('_footer.phtml'); ?>
   
	</body>
</html>


