<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
</head>
	<body>
		<?php
     echo $this->partial('_header.phtml', array (
  			  'user_name' => $this->user_name,
  			  'user_email' => $this->user_email,
          'user_type' => $this->user_type,
  			  'image' => $this->image,
  			  'form2' => $this->form2,
  		)
	);
 ?>
    	<?php echo $this->layout()->content; ?>

        
		<?php echo $this->partial('_footer.phtml'); ?>
   
	</body>
</html>


